/*
------------------------------------------------
Generated by Cradle 2.0.1.0
https://github.com/daterre/Cradle

Original file: BlossomBathroom.html
Story format: Harlowe
------------------------------------------------
*/

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Cradle;
using IStoryThread = System.Collections.Generic.IEnumerable<Cradle.StoryOutput>;
using Cradle.StoryFormats.Harlowe;

public partial class @BlossomBathroom: Cradle.StoryFormats.Harlowe.HarloweStory
{
	#region Variables
	// ---------------

	public class VarDefs: RuntimeVars
	{
		public VarDefs()
		{
		}

	}

	public new VarDefs Vars
	{
		get { return (VarDefs) base.Vars; }
	}

	// ---------------
	#endregion

	#region Initialization
	// ---------------

	public readonly Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros macros1;

	@BlossomBathroom()
	{
		this.StartPassage = "Questions";

		base.Vars = new VarDefs() { Story = this, StrictMode = true };

		macros1 = new Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros() { Story = this };

		base.Init();
		passage1_Init();
		passage2_Init();
		passage3_Init();
		passage4_Init();
		passage5_Init();
		passage6_Init();
		passage7_Init();
		passage8_Init();
		passage9_Init();
	}

	// ---------------
	#endregion

	// .............
	// #1: Questions

	void passage1_Init()
	{
		this.Passages[@"Questions"] = new StoryPassage(@"Questions", new string[]{  }, passage1_Main);
	}

	IStoryThread passage1_Main()
	{
		yield return text("So, I have lots of the products that I use in here. What are some other ");
		yield return link("questions", "questions", null);
		yield return text(" you’re curious about?");
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Exit", "Exit", null);
		yield break;
	}


	// .............
	// #2: questions

	void passage2_Init()
	{
		this.Passages[@"questions"] = new StoryPassage(@"questions", new string[]{  }, passage2_Main);
	}

	IStoryThread passage2_Main()
	{
		yield return link("Are pads, tampons, or cups better?", "Are pads, tampons, or cups better?", null);
		yield return text(" ");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("How can I keep feeling clean every day?", "How can I keep feeling clean every day?", null);
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Exit", "Exit", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #3: Are pads, tampons, or cups better?

	void passage3_Init()
	{
		this.Passages[@"Are pads, tampons, or cups better?"] = new StoryPassage(@"Are pads, tampons, or cups better?", new string[]{  }, passage3_Main);
	}

	IStoryThread passage3_Main()
	{
		yield return text("So, a tampon or a cup can be uncomfortable in the beginning, so lots of girls prefer pads. I used pads at first, and when I got older I started using tampons and a cup. Something nice about those, though, is that they give you more freedom. ");
		using (Group("hook", "")) {
			yield return text("A box of tampons or a cup includes instructions, too, so read them before you use them.");
		}
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return link("How can I keep feeling clean every day?", "How can I keep feeling clean every day?", null);
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Do girls need to douche or use deodorant spray when they have their periods? ", "Do girls need to douche or use deodorant spray when they have their periods? ", null);
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Exit", "Exit", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #4: How can I keep feeling clean every day?

	void passage4_Init()
	{
		this.Passages[@"How can I keep feeling clean every day?"] = new StoryPassage(@"How can I keep feeling clean every day?", new string[]{  }, passage4_Main);
	}

	IStoryThread passage4_Main()
	{
		yield return text("You can try pantiliners. I use them almost every day, and they make me feel fresh.");
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Are pads, tampons, or cups better?", "Are pads, tampons, or cups better?", null);
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Do girls need to douche or use deodorant spray when they have their periods? ", "Do girls need to douche or use deodorant spray when they have their periods? ", null);
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Exit", "Exit", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #5: Do girls need to douche or use deodorant spray when they have their periods? 

	void passage5_Init()
	{
		this.Passages[@"Do girls need to douche or use deodorant spray when they have their periods? "] = new StoryPassage(@"Do girls need to douche or use deodorant spray when they have their periods? ", new string[]{  }, passage5_Main);
	}

	IStoryThread passage5_Main()
	{
		yield return text("Your vaginal area has a different balance than the rest of your body. So douching could increase a possibility of infection if it disrupts this balance in the vagina.");
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Are pads, tampons, or cups better?", "Are pads, tampons, or cups better?", null);
		yield return text(" ");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("How can I keep feeling clean every day?", "How can I keep feeling clean every day?", null);
		yield return lineBreak();
		yield return lineBreak();
		yield return link("What Happens If I Don't Have Pads or Tampons Handy?", "What Happens If I Don't Have Pads or Tampons Handy?", null);
		yield return lineBreak();
		yield return lineBreak();
		yield return link("What's Premenstrual syndrome (PMS)?", "What's Premenstrual syndrome (PMS)?", null);
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Exit", "Exit", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #6: What Happens If I Don't Have Pads or Tampons Handy?

	void passage6_Init()
	{
		this.Passages[@"What Happens If I Don't Have Pads or Tampons Handy?"] = new StoryPassage(@"What Happens If I Don't Have Pads or Tampons Handy?", new string[]{  }, passage6_Main);
	}

	IStoryThread passage6_Main()
	{
		yield return text("You can try a few different things. Sometimes your friends might have extra supplies or visit your school nurse if you’re in school. There are also dispensers in restrooms where you could buy pads or tampons from. You could also call home and someone can bring you what you need. ");
		yield return lineBreak();
		yield return text("The best thing for me is to have extras in my backpack, locker, or bag.");
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return link("What's Premenstrual syndrome (PMS)?", "What's Premenstrual syndrome (PMS)?", null);
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Exit", "Exit", null);
		yield return text(" ");
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return link("I'm done looking around and asking questions", "I'm done looking around and asking questions", null);
		yield break;
	}


	// .............
	// #7: What's Premenstrual syndrome (PMS)?

	void passage7_Init()
	{
		this.Passages[@"What's Premenstrual syndrome (PMS)?"] = new StoryPassage(@"What's Premenstrual syndrome (PMS)?", new string[]{  }, passage7_Main);
	}

	IStoryThread passage7_Main()
	{
		yield return text("That’s something that your body will do to tell you that you might be getting your period soon. Sometimes girls might get moody or irritable, or feel bloated or their breast could feel tender. Lots of times girls won’t experience PMS in their first years. While not all girls experience PMS, for those who do, plenty of rest, exercise, and eating a balanced diet may help.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Exit", "Exit", null);
		yield return text(" ");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("I'm done looking around and asking questions", "I'm done looking around and asking questions", null);
		yield break;
	}


	// .............
	// #8: I'm done looking around and asking questions

	void passage8_Init()
	{
		this.Passages[@"I'm done looking around and asking questions"] = new StoryPassage(@"I'm done looking around and asking questions", new string[]{  }, passage8_Main);
	}

	IStoryThread passage8_Main()
	{
		yield return text(" I hope that this helped you with your questions about periods. It will feel a little different at first, but it’ll soon become a normal part of your life.");
		yield return lineBreak();
		yield return text(" ");
		yield return lineBreak();
		yield return text("Important thing to know is that you are a beautiful girl and that periods are nothing to be scared or worried about.");
		yield break;
	}


	// .............
	// #9: Exit

	void passage9_Init()
	{
		this.Passages[@"Exit"] = new StoryPassage(@"Exit", new string[]{  }, passage9_Main);
	}

	IStoryThread passage9_Main()
	{
		yield return text("Okay. I'm here if you need me.");
		yield break;
	}


}