/*
------------------------------------------------
Generated by Cradle 2.0.1.0
https://github.com/daterre/Cradle

Original file: BlossomBedroom.html
Story format: Harlowe
------------------------------------------------
*/

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Cradle;
using IStoryThread = System.Collections.Generic.IEnumerable<Cradle.StoryOutput>;
using Cradle.StoryFormats.Harlowe;

public partial class @BlossomBedroom: Cradle.StoryFormats.Harlowe.HarloweStory
{
	#region Variables
	// ---------------

	public class VarDefs: RuntimeVars
	{
		public VarDefs()
		{
		}

	}

	public new VarDefs Vars
	{
		get { return (VarDefs) base.Vars; }
	}

	// ---------------
	#endregion

	#region Initialization
	// ---------------

	public readonly Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros macros1;

	@BlossomBedroom()
	{
		this.StartPassage = "Intro";

		base.Vars = new VarDefs() { Story = this, StrictMode = true };

		macros1 = new Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros() { Story = this };

		base.Init();
		passage1_Init();
		passage2_Init();
		passage3_Init();
		passage4_Init();
		passage5_Init();
		passage6_Init();
		passage7_Init();
		passage8_Init();
		passage9_Init();
		passage10_Init();
		passage11_Init();
		passage12_Init();
		passage13_Init();
		passage14_Init();
		passage15_Init();
		passage16_Init();
	}

	// ---------------
	#endregion

	// .............
	// #1: Intro

	void passage1_Init()
	{
		this.Passages[@"Intro"] = new StoryPassage(@"Intro", new string[]{  }, passage1_Main);
	}

	IStoryThread passage1_Main()
	{
		yield return text("You were in the bathroom and noticed something different. There are little spots of blood on your underwear.");
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return link("You’re worried. What if your family finds out and teases you?", "You’re worried. What if your family finds out and teases you?", null);
		yield return lineBreak();
		yield return lineBreak();
		yield return link("That’s exciting! You got your period!", "That’s exciting! You got your period!", null);
		yield return lineBreak();
		yield break;
	}


	// .............
	// #2: You’re worried. What if your family finds out and teases you?

	void passage2_Init()
	{
		this.Passages[@"You’re worried. What if your family finds out and teases you?"] = new StoryPassage(@"You’re worried. What if your family finds out and teases you?", new string[]{  }, passage2_Main);
	}

	IStoryThread passage2_Main()
	{
		yield return text("Oh, I won’t tease you. The same thing happened to me, too. I was 11 years old when I got my period.");
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Next ", "That’s exciting! You got your period!", null);
		yield return lineBreak();
		yield break;
	}


	// .............
	// #3: Why do only girls have periods and not boys? 

	void passage3_Init()
	{
		this.Passages[@"Why do only girls have periods and not boys? "] = new StoryPassage(@"Why do only girls have periods and not boys? ", new string[]{  }, passage3_Main);
	}

	IStoryThread passage3_Main()
	{
		yield return text("Well, boys have different body parts and their bodies change differently like their voices deepen and their facial hair starts growing. And girls get their period because their uterus changes, and getting your period means you can have a baby.");
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Do girls have their periods for the rest of their lives? ", "Do girls have their periods for the rest of their lives? ", null);
		yield return lineBreak();
		yield return lineBreak();
		yield return link("How long does a period last?", "How long does a period last?", null);
		yield break;
	}


	// .............
	// #4: Do girls have their periods for the rest of their lives? 

	void passage4_Init()
	{
		this.Passages[@"Do girls have their periods for the rest of their lives? "] = new StoryPassage(@"Do girls have their periods for the rest of their lives? ", new string[]{  }, passage4_Main);
	}

	IStoryThread passage4_Main()
	{
		yield return text("You’ll have periods for a while, but when you’re in your 40’s or 50’s you won’t have them anymore.");
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return link("How long does a period last?", "How long does a period last?", null);
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Why do only girls have periods and not boys? ", "Why do only girls have periods and not boys? ", null);
		yield break;
	}


	// .............
	// #5: How long does a period last?

	void passage5_Init()
	{
		this.Passages[@"How long does a period last?"] = new StoryPassage(@"How long does a period last?", new string[]{  }, passage5_Main);
	}

	IStoryThread passage5_Main()
	{
		yield return text("It’s different for every girl. Mine last about six days, but some girls have them for 3 days. Others have it for a week. ");
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return link("How much blood do I lose during my period?", "How much blood do I lose during my period?", null);
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Will it Hurt When I Get My Period?", "Will it Hurt When I Get My Period?", null);
		yield break;
	}


	// .............
	// #6: How much blood do I lose during my period?

	void passage6_Init()
	{
		this.Passages[@"How much blood do I lose during my period?"] = new StoryPassage(@"How much blood do I lose during my period?", new string[]{  }, passage6_Main);
	}

	IStoryThread passage6_Main()
	{
		yield return text("It’s different for each period. Sometimes mine are lighter and other times they’re heavier. Most of the time it is about ¼ cup of blood, but your body makes up for it very quickly.");
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Will it Hurt When I Get My Period?", "Will it Hurt When I Get My Period?", null);
		yield return lineBreak();
		yield return lineBreak();
		yield return link("What Will I do If My Period Starts All of a Sudden?", "What Will I do If My Period Starts All of a Sudden?", null);
		yield break;
	}


	// .............
	// #7: Will it Hurt When I Get My Period?

	void passage7_Init()
	{
		this.Passages[@"Will it Hurt When I Get My Period?"] = new StoryPassage(@"Will it Hurt When I Get My Period?", new string[]{  }, passage7_Main);
	}

	IStoryThread passage7_Main()
	{
		yield return text("I worried about this, too. ");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("Most of the time it doesn’t hurt, but sometimes I feel cramps, headaches or backaches. This doesn’t last very long. If you keep feeling in pain, you can try a hot bath or press a hot towel where you hurt. You can also go to the store with mom or dad to get some medicine that can help you feel better.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("But if you’re hurting a lot, you should let mom or dad know so you can go visit a doctor.");
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return link("What Will I do If My Period Starts All of a Sudden?", "What Will I do If My Period Starts All of a Sudden?", null);
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Is there something that I can’t do when I have my period?", "Is there something that I can’t do when I have my period?", null);
		yield break;
	}


	// .............
	// #8: What Will I do If My Period Starts All of a Sudden?

	void passage8_Init()
	{
		this.Passages[@"What Will I do If My Period Starts All of a Sudden?"] = new StoryPassage(@"What Will I do If My Period Starts All of a Sudden?", new string[]{  }, passage8_Main);
	}

	IStoryThread passage8_Main()
	{
		yield return text("I worried about that, too! You can keep a period diary of the days you had your last period to estimate when your next one will be.");
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return text("It’s not easy to know the exact day it will start, so I like to keep a few extra pads or tampons with me in case I’m caught off guard. You can make a kit and keep it in your purse or backpack at all times.");
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return text("Sometimes I visited a school nurse, too, because mine had extra hygiene supplies.");
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Will it Hurt When I Get My Period?", "Will it Hurt When I Get My Period?", null);
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Is there something that I can’t do when I have my period?", "Is there something that I can’t do when I have my period?", null);
		yield break;
	}


	// .............
	// #9: Is there something that I can’t do when I have my period?

	void passage9_Init()
	{
		this.Passages[@"Is there something that I can’t do when I have my period?"] = new StoryPassage(@"Is there something that I can’t do when I have my period?", new string[]{  }, passage9_Main);
	}

	IStoryThread passage9_Main()
	{
		yield return text("You can still do everything you would when you don’t have your period. ");
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Can I Still Play Sports When I'm have my period?", "Can I Still Play Sports When I'm have my period?", null);
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Will others Know I have my period?", "Will others Know I have my period?", null);
		yield break;
	}


	// .............
	// #10: Can I Still Play Sports When I'm have my period?

	void passage10_Init()
	{
		this.Passages[@"Can I Still Play Sports When I'm have my period?"] = new StoryPassage(@"Can I Still Play Sports When I'm have my period?", new string[]{  }, passage10_Main);
	}

	IStoryThread passage10_Main()
	{
		yield return text("Of course you can! You might want to change your pads more frequently, though.");
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return link("What about swimming?", "What about swimming?", null);
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Will others Know I have my period?", "Will others Know I have my period?", null);
		yield break;
	}


	// .............
	// #11: Will others Know I have my period?

	void passage11_Init()
	{
		this.Passages[@"Will others Know I have my period?"] = new StoryPassage(@"Will others Know I have my period?", new string[]{  }, passage11_Main);
	}

	IStoryThread passage11_Main()
	{
		yield return text("Others won’t know unless you choose to tell them.");
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Can I Still Play Sports When I'm have my period?", "Can I Still Play Sports When I'm have my period?", null);
		yield return lineBreak();
		yield return lineBreak();
		yield return link("What If Blood Leaks Through My Underwear and Pants?", "What If Blood Leaks Through My Underwear and Pants?", null);
		yield break;
	}


	// .............
	// #12: What about swimming?

	void passage12_Init()
	{
		this.Passages[@"What about swimming?"] = new StoryPassage(@"What about swimming?", new string[]{  }, passage12_Main);
	}

	IStoryThread passage12_Main()
	{
		yield return text("If you want to go swimming, then you will want to use a tampon or a cup. It’s okay if you don’t feel comfortable using those. I didn’t use them in the beginning, so I didn’t go swimming then.");
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Will others Know I have my period?", "Will others Know I have my period?", null);
		yield break;
	}


	// .............
	// #13: What If Blood Leaks Through My Underwear and Pants?

	void passage13_Init()
	{
		this.Passages[@"What If Blood Leaks Through My Underwear and Pants?"] = new StoryPassage(@"What If Blood Leaks Through My Underwear and Pants?", new string[]{  }, passage13_Main);
	}

	IStoryThread passage13_Main()
	{
		yield return text("That happened to me a few times. I either wear dark-colored underwear and pants. Sometimes I’d also use a sweater to tie around my waist to hide the spot. Then I go to the bathroom and get a fresh pad, tampon or empty my cup.");
		yield return lineBreak();
		yield return text("If my period is heavy, I’d wear a pad with a tampon or a cup.");
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return link("How do I wash my underwear and pants when I get home?", "How do I wash my underwear and pants when I get home?", null);
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Let’s go to the bathroom and look at some of the products that many girls use.", "Let’s go to the bathroom and look at some of the products that many girls use.", null);
		yield break;
	}


	// .............
	// #14: How do I wash my underwear and pants when I get home?

	void passage14_Init()
	{
		this.Passages[@"How do I wash my underwear and pants when I get home?"] = new StoryPassage(@"How do I wash my underwear and pants when I get home?", new string[]{  }, passage14_Main);
	}

	IStoryThread passage14_Main()
	{
		yield return text("Make sure you wash your clothes with cold water as soon as possible. Sometimes, the stain comes out and sometimes it doesn't. ");
		using (Group("hook", "")) {
			yield return text("But to avoid getting your clothes stained, change your pads and tampons or empty your cup regularly. I keep extras in my backpack or locker, too.");
		}
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Let’s go to the bathroom and look at some of the products that many girls use.", "Let’s go to the bathroom and look at some of the products that many girls use.", null);
		yield break;
	}


	// .............
	// #15: Let’s go to the bathroom and look at some of the products that many girls use.

	void passage15_Init()
	{
		this.Passages[@"Let’s go to the bathroom and look at some of the products that many girls use."] = new StoryPassage(@"Let’s go to the bathroom and look at some of the products that many girls use.", new string[]{  }, passage15_Main);
	}

	IStoryThread passage15_Main()
	{
		yield return text("Double-click this passage to edit it.");
		yield break;
	}


	// .............
	// #16: That’s exciting! You got your period!

	void passage16_Init()
	{
		this.Passages[@"That’s exciting! You got your period!"] = new StoryPassage(@"That’s exciting! You got your period!", new string[]{  }, passage16_Main);
	}

	IStoryThread passage16_Main()
	{
		yield return text("This means that you’re growing up, and you’re becoming a woman.");
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Why do only girls have periods and not boys? ", "Why do only girls have periods and not boys? ", null);
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Do girls have their periods for the rest of their lives? ", "Do girls have their periods for the rest of their lives? ", null);
		yield break;
	}


}